### PR TITLE
Templates added

### LINKED ISSUE #1: Make a issue template
Make an issue template that helps the other users to exactly classify bug and feature.
Includes how the code function in Laptop browser and mobile browser.  
Also, include various checks like build passing etc.
Depends on your creativity we are open to brain-storming.

### PR DESCRIPTION
**Pull request by Sapna2001**
Issue and PR templates added.

Fixes #1

### CODE REVIEW

**Comment by Sapna2001** [comment]
@helios1101 please review this.

**Comment by helios1101** [comment]
Hi @Sapna2001 
That looks great, however can you add steps to replicate the bug.
Would recomend exploring some more, templates for better understanding.
Thanks for the contribution :)

**Comment by helios1101** [comment]
Hi @Sapna2001 
Great work ! Looks great as of now.
Kudos :)
Show off your contribution on social media as well. !!

**Comment by helios1101** [comment]
Hi @Sapna2001 
Please show off your contribution in #28 as well.

**Pull request merged**
