### PR TITLE
Designed the Courses page for student Section

### LINKED ISSUE #32: Creating the courses page for students section
**I want to create the courses page of student section of website  using flutter**

image

### PR DESCRIPTION
**Pull request by Akanksha-Pant**
Designed the Courses page for student Section
I have designed the courses page for the student section. I have tried to exactly replicate the page that was present on the website. The whole page has a similar UI to that of the webpage.I have also added a drawer to navigate to various other part of the app.  This resolves #32 

# Screenshots
Screenshots of the proposed changes compared with the current version of the project
Image1
Image2
Image3

### CODE REVIEW

**Comment by Akanksha-Pant** [comment]
@helios1101  May I know what checks have failed so I can enhance my code?

**Comment by helios1101** [comment]
@Akanksha-Pant 
Checkstyle errors have occured, not an issue. 
Would you mind, adding a video of app in action. 
Once, it's done we can proceed with reviewing changes.

**Comment by Akanksha-Pant** [comment]
@helios1101 Hey You can click on the image to watch the video. I have tried to cover everything I can.
[](http://www.youtube.com/watch?v=LETF0QoaD7I "Course Page")

**Review by helios1101 — APPROVED** [review]

**Comment by helios1101** [comment]
Hi @Akanksha-Pant 
Changes look great, would you mind adding the working video for the same, so that it becomes eligible for merge.
Thanks :)

**Comment by Akanksha-Pant** [comment]
Hey, I have already added the video above ,you just have to click on it. I hope it's working. Do you want me to add the video in the project?

**Comment by helios1101** [comment]
Show off your contributions in #28 and share with yopur friends.
Haapy Contribution !

**Pull request merged**
