### PR TITLE
Homescreen added.

### PR DESCRIPTION
**Pull request by Himanshuranjan30**
# Description
Designed and developed a homescreen for the codeasylum website.

Fixes # [ISSUE]

# Type of Change:

- Code
- Quality Assurance
- User Interface
- Homescreen

# Screenshots
Screenshots of the proposed changes compared with the current version of the
Video Link

https://drive.google.com/file/d/1abnVMQzkazZskKzindCJXTB5kIoZpMtG/view?usp=sharing
 
cod1
code2

Issue link: https://github.com/HakinCodes/CodeAsylums-App/issues/11

# Checklist:

- [ ] My code follows the style guidelines(Clean Code) of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests/screenshots(If any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by helios1101** [comment]
Hi @Himanshuranjan30 
Great work ! will review this weekend, make sure to give your best shot !
All the best

**Comment by Himanshuranjan30** [comment]
Looking forward for the merge. Thanks @helios1101

**Comment by Himanshuranjan30** [comment]
any updates with the merge yet @helios1101 ?

**Comment by helios1101** [comment]
Hi @Himanshuranjan30 
Just got engrossed with other commitments and stuffs.
The action item is on me, no worries.
Rest assured. :)

**Review by helios1101 — APPROVED** [review]

**Comment by helios1101** [comment]
Congrats @Himanshuranjan30 
Show off your contribution in #28 and share with your friends.
Happy contribution ! :)

**Comment by Himanshuranjan30** [comment]
Thanks @helios1101 ! Looking forward to many more contributions in the future. Open source FTW.

**Comment by Himanshuranjan30** [comment]
> **Try to make more responsive used the following widget**
> and replace all the height and width with media query
> 
> A responsive app layout its UI according to the size and shape of the screen or window. This is especially necessary when the same app can run on a variety of devices, from a watch, phone, tablet, to a laptop or desktop computer. When the user resizes the window on a laptop or desktop, or changes the orientation of the phone or tablet, the app should respond by rearranging the UI accordingly.
> 
> Flutter allows you to create apps that self-adapt to the device’s screen size and orientation.
> 
> There are two basic approaches to creating Flutter apps with responsive design:

Sure,I'll work on this.Thanks for the feedback.

**Pull request merged**
